name: "Install Conan dependencies"
description: "Runs `conan install` for building Overte."
inputs:
   qt_source:
     required: false
     description: "Where to get Qt from. See our conanfile.py for the available options."
   cppstd:
     required: false
     description: "Which C++ standard to use."
   build_type:
     required: false
     description: "Which CMake build type to use. E.g. Release, RelWithDebInfo, Debug"
     default: Release
   conan_profile:
     required: false
     description: "Which Conan profile to use. E.g. './tools/conan-profiles/vs-22-release'. Uses Conan's default if not defined, which may or may not work."
     default: default
runs:
  using: "composite"
  steps:
  - name: Install Conan dependencies
    shell: bash
    run: |
      # Run twice to work around OpenSSL not being found. See: https://github.com/overte-org/overte-conan-recipes/issues/1
      for counter in {1..2}; do
        conan install . -s compiler.cppstd=${{ inputs.cppstd }} -s build_type=${{ inputs.build_type }} -o '&:qt_source='${{ inputs.qt_source }} -b missing -pr=${{ inputs.conan_profile }} -of build --format=json > build.json
      done
